---
title: "Policebrutality_plot1"
author: "Rana Gahwagy"
date: "2023-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r}
library(ggplot2)
library(janitor)
library(tidyverse)
library(readr)
library(ggpubr)
library(readxl)
library(maptools)
library(maps)
library(ggforce)
library(gganimate)
#library(htmlwidgets)
#library(htmltools)
library(leaflet)
library("leafletCN")
library(patchwork)
library(tigris)
library(leaftime)
library(censusapi)
library(leaflet.minicharts)
library(sf)
```


```{r, results='hide'}
#data 
police_violence <- read_csv("Mapping Police Violence - MPV.csv")

#cleaning data 
police_violence <- police_violence %>% clean_names() %>%
  mutate(victims_gender = as.factor(victims_gender), victims_race = as.factor(victims_race), 
         state = as.factor(state), year = as.factor(date_of_incident_month_day_year))

#total number of killings by state by year by race and gender 
killing_by_state <- police_violence %>%
  group_by(state) %>%
  summarize(total=n())

killing_by_gender <- police_violence %>%
  group_by(state, victims_gender) %>%
  summarize(total=n()) %>%
  pivot_wider(names_from = victims_gender, values_from = total) 
killing_by_gender$total <- killing_by_state$total

killing_by_race <- police_violence %>%
  group_by(state, victims_race) %>%
  summarize(total=n())%>%
  pivot_wider(names_from = victims_race, values_from = total) 
killing_by_race$total <- killing_by_state$total

killing_by_year <- police_violence %>%
  group_by(state, year) %>%
  summarize(total=n())

# also add total per capita 
# get cenus data via API
# Add key to .Renviron
Sys.setenv(CENSUS_KEY="5751ee86b72f03b9ea3fbd1f7bd9ff64fe7fc4ae")
# Reload .Renviron
readRenviron("~/.Renviron")
# Check to see that the expected key is output in your R console
Sys.getenv("CENSUS_KEY")

state_pop <-  getCensus(name="acs/acs5", 
                        vintage=2019,
                        key = Sys.getenv("CENSUS_KEY"),
                        vars=c("NAME", "B01003_001E"), 
                        region="state:*")
# Cleaning up the column names
colnames(state_pop) <- c("state_id", "NAME", "population")
state_pop$state_id <- as.numeric(state_pop$state_id)
#abbrevated list
state_off <- data.frame(state.abb, state.name)
# Cleaning up the names for easier joining
colnames(state_off) <- c("state", "NAME")
# Joining state population dataframe to relationship file
state_pop <- left_join(state_pop, state_off)
# manually adding  DC or Puerto Rico
state_pop$state <- ifelse(state_pop$NAME=="District of Columbia", "DC", as.character(state_pop$state))
state_pop$state <- ifelse(state_pop$NAME=="Puerto Rico", "PR", as.character(state_pop$state))
# Joining Starbucks dataframe to adjusted state population dataframe
pv_state_pop <- left_join(killing_by_state, state_pop)
# Calculating per Starbucks stores 100,000 residents and rounding to 2 digits
pv_state_pop$per_capita <- round(pv_state_pop$total/pv_state_pop$population*100000,2)

#definging states shapefile
states <- states(cb=T)
#extracting coordenates 
states_coord <- states %>% 
  st_point_on_surface() %>% 
  st_coordinates() %>% 
  as_tibble() %>% 
  rename(lon = 1, lat = 2) %>% 
  bind_cols(states %>% st_drop_geometry())

#joining state data to shape files 
states_merged_pv <- geo_join(states, killing_by_state, "STUSPS", "state")
states_merged_pv_pop <- geo_join(states, pv_state_pop, "STUSPS", "state")
#for the mini chart
states_merged_pv_gender <- inner_join(states_coord, killing_by_gender, by= c("STUSPS" ="state"))
states_merged_pv_race <- inner_join(states_coord, killing_by_race, by= c("STUSPS" ="state"))
states_merged_pv_year <- inner_join(states_coord, killing_by_year, by= c("STUSPS" ="state"))
```

```{r, results='hide'}
pal <- colorBin("Reds", states_merged_pv$total, bins= 7)
pal_pop <- colorBin("Reds", states_merged_pv_pop$per_capita, bins = 5)
pal_race <- c("#845EC2", "#D65DB1","#FF6F91","#0081CF", "#FF9671", "#FFC75F", "#F9F871" )
pal_gender <- c("#845EC2", "#F3C5FF","#00C9A7","#FEFEDF" )


# pop-up text 
popup_pv <- paste0("Total: ", as.character(states_merged_pv$total))

```

```{r}
pv_map_race <- leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addMinicharts(lng = states_merged_pv_race$lon, 
                lat = states_merged_pv_race$lat, 
                type = "pie", 
                chartdata = states_merged_pv_race[, c( "Asian", "Black", "Hispanic", "Native American",
                                                       "Pacific Islander", "White", "Unknown race")],
                colorPalette = pal_race, 
                width = 60 * sqrt(states_merged_pv_race$total) / sqrt(max(states_merged_pv_race$total)), 
                transitionTime = 0)
pv_map_race
```

